/**
 * Footer Component Loader
 * Loads the centralized footer component into all pages
 * Ensures consistency and theme compatibility
 */

class FooterLoader {
    constructor() {
        this.footerPath = './components/footer.html';
        this.footerContainer = null;
    }

    /**
     * Initialize the footer loader
     */
    init() {
        // Create footer container if it doesn't exist
        this.createFooterContainer();
        
        // Load the footer component
        this.loadFooter();
    }

    /**
     * Create the footer container element
     */
    createFooterContainer() {
        // Check if footer container already exists
        this.footerContainer = document.getElementById('footer-container');
        
        if (!this.footerContainer) {
            // Create footer container
            this.footerContainer = document.createElement('div');
            this.footerContainer.id = 'footer-container';
            
            // Insert before the closing body tag
            document.body.appendChild(this.footerContainer);
        }
    }

    /**
     * Load the footer component from the external file
     */
    async loadFooter() {
        try {
            // Embedded footer HTML (to avoid CORS issues with file:// protocol)
            const footerHTML = `
<!-- 
===========================================
FOOTER COMPONENT
===========================================
This is the centralized footer that appears on all pages.
Edit this file to change the footer across the entire website.
    // ==========================================
    // BRAND LOGO CONFIGURATION
    // ==========================================
    // Brand settings are managed by Configurations/brand-config.js
-->
<footer class="footer">
    <div class="container">
        <div class="footer-content">
            <div class="footer-section">
                <!-- Brand Section - Managed by brand-config.js -->
                <div class="footer-brand">
                    <!-- Brand content will be dynamically generated by brand-config.js -->
                </div>
                
                <p>Your trusted source for gaming laptop reviews and recommendations.</p>
                <p>We've been helping gamers find the perfect gaming laptops since 2020.</p>
            </div>
            
            <div class="footer-section">
                <h4>Quick Links</h4>
                <ul>
                    <li><a href="./index.html#reviews">Reviews</a></li>
                    <li><a href="./index.html#comparison">Comparison</a></li>
                    <li><a href="./blog.html">Blog</a></li>
                    <li><a href="./contact.html">Contact</a></li>
                    <li><a href="./streaming.html">Streaming</a></li>
                    <li><a href="./podcast.html">Podcasts</a></li>
                </ul>
            </div>
            
            <div class="footer-section">
                <h4>Top Laptops</h4>
                <ul>
                    <li><a href="./index.html#editors-choice-review">MacBook Pro M4 Max</a></li>
                    <li><a href="./index.html#review-1">ASUS ZenBook Pro 14 OLED</a></li>
                    <li><a href="./index.html#review-2">Dell XPS 15 Plus</a></li>
                    <li><a href="./index.html#top10">All Rankings</a></li>
                </ul>
            </div>
            
            <div class="footer-section">
                <h4>Resources</h4>
                <ul>
                    <li><a href="./contact.html#faq">FAQ</a></li>
                    <li><a href="./contact.html">Support</a></li>
                    <li><a href="#newsletter">Newsletter</a></li>
                </ul>
            </div>
            
            <div class="footer-section">
                <h4>Connect</h4>
                <p>Follow us for the latest gaming laptop news and reviews.</p>
                <ul>
                    <li><a href="https://x.com/yourbrand" target="_blank">X</a></li>
                    <li><a href="https://facebook.com/yourbrand" target="_blank">Facebook</a></li>
                    <li><a href="https://instagram.com/yourbrand" target="_blank">Instagram</a></li>
                    <li><a href="https://youtube.com/yourbrand" target="_blank">YouTube</a></li>
                </ul>
            </div>
            
            <div class="footer-section">
                <h4>Legal</h4>
                <ul>
                    <li><a href="./privacy.html">Privacy Policy</a></li>
                    <li><a href="./disclaimer.html">Affiliate Disclosure</a></li>
                    <li><a href="./cookies.html">Cookie Policy</a></li>
                </ul>
            </div>
        </div>
        
        <!-- Affiliate Disclosure -->
        <div class="affiliate-disclosure">
            <p><strong>Affiliate Disclosure:</strong> This website contains affiliate links. We may earn a commission when you click on links or make purchases through our site, at no additional cost to you.</p>
        </div>
        
        <div class="footer-bottom">
            <p>&copy; 2025 <span class="footer-brand-name"></span>. All rights reserved.</p>
        </div>
    </div>
</footer>`;
            
            // Insert the footer HTML
            this.footerContainer.innerHTML = footerHTML;
            
            // Apply theme-aware styling after loading
            this.applyThemeAwareStyles();
            
            console.log('Footer loaded successfully');
            
        } catch (error) {
            console.error('Error loading footer:', error);
            
            // Fallback: create a basic footer
            this.createFallbackFooter();
        }
    }

    /**
     * Apply theme-aware styles to the loaded footer
     */
    applyThemeAwareStyles() {
        // The CSS theme styles will automatically apply
        // This method can be extended for additional theme-specific logic
        
        // Ensure footer links have proper theme classes
        const footerLinks = this.footerContainer.querySelectorAll('a');
        footerLinks.forEach(link => {
            // Add any additional theme-specific classes if needed
            link.classList.add('footer-link');
        });
    }

    /**
     * Create a fallback footer if the component fails to load
     */
    createFallbackFooter() {
        const fallbackFooter = `
            <footer class="footer">
                <div class="container">
                    <div class="footer-content">
                        <div class="footer-section">
                            <h4>{{BRAND_NAME}}</h4>
                            <p>Your trusted source for {{NICHE}} reviews.</p>
                        </div>
                        <div class="footer-section">
                            <h4>Quick Links</h4>
                            <ul>
                                <li><a href="#reviews">Reviews</a></li>
                                <li><a href="./blog.html">Blog</a></li>
                            </ul>
                        </div>
                        <div class="footer-section">
                            <h4>Legal</h4>
                            <ul>
                                <li><a href="./privacy.html">Privacy Policy</a></li>
                                <li><a href="./disclaimer.html">Disclaimer</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="footer-bottom">
                        <p>&copy; 2025 {{BRAND_NAME}}. All rights reserved.</p>
                    </div>
                </div>
            </footer>
        `;
        
        this.footerContainer.innerHTML = fallbackFooter;
        console.log('Fallback footer loaded');
    }

    /**
     * Update footer content dynamically
     * @param {string} section - The section to update
     * @param {string} content - The new content
     */
    updateFooterSection(section, content) {
        const sectionElement = this.footerContainer.querySelector(`[data-section="${section}"]`);
        if (sectionElement) {
            sectionElement.innerHTML = content;
        }
    }
}

// Initialize footer loader when DOM is ready
document.addEventListener('DOMContentLoaded', () => {
    const footerLoader = new FooterLoader();
    footerLoader.init();
});

// Export for use in other scripts
window.FooterLoader = FooterLoader; 